export const templates = {
    seasons: {
        name: 'Seasons',
        imageUrl: 'https://placehold.co/600x800/86efac/000000?text=Seasons',
        description: 'Experience the beauty of every season.',
        isPolaroid: false,
        seasons: ['Spring', 'Summer', 'Autumn', 'Winter'],
        prompts: {
            Spring: [
                { id: 'Cherry Blossoms', base: 'A portrait of a single person under a canopy of blooming cherry blossom trees, with petals gently falling.' },
                { id: 'Flower Field', base: 'A joyful photo of a single person in a field of colorful wildflowers under a clear blue sky.' },
                { id: 'April Showers', base: 'A playful photo of a single person with a colorful umbrella during a light spring rain.' },
                { id: 'Garden Path', base: 'A serene photo of a single person walking down a lush green garden path with fresh spring foliage.' },
                { id: 'Picnic', base: 'A classic spring picnic scene featuring a single person with a checkered blanket and a basket of fresh fruit.' },
                { id: 'New Beginnings', base: 'A hopeful portrait of a single person with the sunrise in the background, symbolizing a new start.' },
            ],
            Summer: [
                { id: 'Beach Sunset', base: 'A silhouette photo of a single person on a beach during a vibrant summer sunset.' },
                { id: 'Ice Cream Fun', base: 'A fun, candid shot of a single person enjoying a colorful ice cream cone on a sunny day.' },
                { id: 'Poolside', base: 'A relaxed photo of a single person lounging by a crystal clear swimming pool.' },
                { id: 'Road Trip', base: 'An adventurous shot of a single person in a convertible car on an open road with mountains in the background.' },
                { id: 'Stargazing', base: 'A magical photo of a single person looking up at a starry summer night sky.' },
                { id: 'Boardwalk', base: 'A lively photo of a single person on a bustling boardwalk with carnival lights.' },
            ],
            Autumn: [
                { id: 'Pumpkin Patch', base: 'A candid photo of a single person in a rustic pumpkin patch, surrounded by pumpkins.' },
                { id: 'Falling Leaves', base: 'A joyful photo of a single person with colorful autumn leaves falling all around.' },
                { id: 'Cozy Sweater', base: 'A cozy portrait of a single person wearing a warm sweater, holding a steaming mug of coffee or tea.' },
                { id: 'Apple Picking', base: 'A sunny day photo of a single person in an apple orchard, picking fresh apples.' },
                { id: 'Corn Maze', base: 'An adventurous photo of a single person peeking out from a tall corn maze.' },
                { id: 'Hayride', base: 'A fun photo of a single person sitting on hay bales on a tractor hayride.' },
            ],
            Winter: [
                { id: 'Snowy Forest', base: 'A peaceful portrait of a single person in a quiet, snow-covered forest.' },
                { id: 'Ice Skating', base: 'An energetic photo of a single person ice skating on a frozen pond or rink.' },
                { id: 'By the Fireplace', base: 'A warm and cozy photo of a single person sitting by a crackling fireplace with a good book.' },
                { id: 'Building a Snowman', base: 'A playful photo of a single person building a snowman with a carrot nose and scarf.' },
                { id: 'City Lights', base: 'A photo of a single person in a city at night with festive holiday lights and falling snow.' },
                { id: 'Mountain View', base: 'A majestic photo of a single person overlooking a snowy mountain landscape.' },
            ],
        }
    },
    holidays: {
        name: 'Holidays & Festivals',
        imageUrl: 'https://placehold.co/600x700/ef4444/ffffff?text=Holidays',
        description: 'Celebrate festive times from around the world.',
        isPolaroid: false,
        holidays: ['Christmas', 'Hanukkah', 'New Year', 'Chinese New Year', 'Ramadan', 'Eid al-Adha', 'Eid al-Fitr', 'Easter', 'Valentine’s Day', 'Diwali', 'Halloween', 'Holi', 'Independence Day', 'Thanksgiving', 'Boxing Day', 'St Patricks Day', 'Hanami', 'Oktoberfest', 'Carnival', 'Mardi Gras', 'Obon', 'Day of the Dead', 'Songkran'],
        prompts: {
            Christmas: [
                { id: "Opening a Gift", base: "A joyful photo of a single person opening a glowing gift under a decorated Christmas tree." },
                { id: "Baking Cookies", base: "A cozy kitchen scene with a single person decorating Christmas cookies with colorful icing." },
                { id: "By the Fireplace", base: "A warm portrait of a single person by a crackling fireplace, holding a mug of hot cocoa." },
                { id: "Snowy Walk", base: "A single person bundled-up for a walk through a snowy landscape with festive lights in the background." },
                { id: "Holiday Caroling", base: "A classic scene of a single person singing carols, holding a songbook on a decorated porch." },
                { id: "Mistletoe Moment", base: "A sweet, solo portrait of a person puckering up for a kiss under the mistletoe." },
            ],
            Hanukkah: [
                { id: "Lighting the Menorah", base: "A beautiful photo of a single person lighting the menorah, with the candles casting a warm glow." },
                { id: "Playing Dreidel", base: "A fun, action shot of a single person spinning the dreidel game with gelt." },
                { id: "Making Latkes", base: "A happy kitchen scene with a single person making or enjoying freshly made latkes." },
                { id: "Enjoying Sufganiyot", base: "A close-up shot of a single person enjoying a powdered sugar sufganiyot (jelly donut)." },
                { id: "Hanukkah Gelt", base: "A photo of a single person with a shower of chocolate gelt coins." },
                { id: "Celebratory Portrait", base: "A warm portrait of a single person, celebrating the festival of lights." },
            ],
            "New Year": [
                { id: "Confetti Pop", base: "A celebratory moment of a single person with confetti popping at midnight." },
                { id: "Sparkler Fun", base: "A magical photo of a single person at night, drawing shapes with a glowing sparkler." },
                { id: "Toasting the New Year", base: "A festive shot of a single person toasting with champagne or sparkling cider." },
                { id: "Watching Fireworks", base: "A silhouette of a single person against a backdrop of colorful New Year's fireworks." },
                { id: "Dressed for the Ball", base: "A glamorous photo of a single person dressed in festive New Year's Eve attire." },
                { id: "Clock at Midnight", base: "A dramatic pose of a single person in front of a large clock striking twelve." },
            ],
            "Chinese New Year": [
                { id: "Lantern Festival", base: "A stunning photo of a single person surrounded by glowing red lanterns at night." },
                { id: "Dragon Dance", base: "An energetic shot with a single person in the foreground and a colorful dragon dance in the background." },
                { id: "Red Envelope", base: "A happy photo of a single person holding a traditional red envelope." },
                { id: "Enjoying the Feast", base: "A scene of a single person at a table enjoying a festive meal." },
                { id: "Traditional Attire", base: "A beautiful portrait of a single person wearing traditional Chinese New Year clothing." },
                { id: "Firecracker Lights", base: "A fun, safe photo with the bright lights of firecrackers in the background." },
            ],
            Ramadan: [
                { id: "Breaking Fast", base: "A serene photo of a single person breaking fast (Iftar) with dates and water at sunset." },
                { id: "Reading Quran", base: "A reflective portrait of a single person reading the Quran in a beautifully lit room." },
                { id: "Night Prayer", base: "A photo of a single person praying peacefully during the night." },
                { id: "Mosque Lights", base: "A portrait of a single person in front of a mosque decorated with lights for Ramadan." },
                { id: "Preparing Suhoor", base: "A single person preparing a meal for Suhoor before sunrise." },
                { id: "Spirit of Giving", base: "A single person sharing a plate of food, embodying the spirit of giving." },
            ],
            "Eid al-Adha": [
                { id: "Morning Prayers", base: "A serene photo of a single person in elegant attire, preparing for or returning from Eid prayers." },
                { id: "Festive Feast", base: "A joyful portrait of a single person at a table laden with a festive Eid feast." },
                { id: "Holding a Gift", base: "A heartwarming moment of a single person holding a gift." },
                { id: "Elegant Attire", base: "A full-body portrait of a single person showcasing beautiful, traditional Eid clothing." },
                { id: "Spirit of Celebration", base: "A photo of a single person sharing food and celebrating." },
                { id: "Solo Portrait", base: "A beautiful portrait of a single person celebrating Eid." },
            ],
            "Eid al-Fitr": [
                { id: "Moon Sighting", base: "A hopeful photo of a single person looking at the new moon that marks the end of Ramadan." },
                { id: "Enjoying Sweets", base: "A delightful photo of a single person enjoying traditional Eid sweets and treats." },
                { id: "Decorated Home", base: "A portrait of a single person in a home beautifully decorated with lights and ornaments for Eid." },
                { id: "New Clothes", base: "A stylish photo of a single person showing off brand new clothes for the Eid celebration." },
                { id: "Moment of Giving", base: "A candid photo of a single person representing the spirit of giving (zakat al-fitr)." },
                { id: "Joyful Portrait", base: "A joyful portrait of a single person after morning prayers." },
            ],
            Easter: [
                { id: "Egg Hunt", base: "A fun, candid photo of a single person searching for colorful Easter eggs in a spring garden." },
                { id: "Pastel Portrait", base: "A soft, lovely portrait of a single person in pastel-colored spring attire." },
                { id: "With a Bunny", base: "A cute photo of a single person gently holding a fluffy Easter bunny." },
                { id: "Decorating Eggs", base: "A creative shot focused on a single person's hands intricately decorating Easter eggs." },
                { id: "Spring Brunch", base: "An elegant photo of a single person at a beautiful Easter brunch table setting." },
                { id: "Church Portrait", base: "A respectful and serene photo of a single person in a beautifully decorated church for Easter service." },
            ],
            "Valentine’s Day": [
                { id: "Rose Petals", base: "A romantic portrait of a single person with red rose petals falling around." },
                { id: "Heart-Shaped Box", base: "A sweet photo of a single person holding a heart-shaped box of chocolates." },
                { id: "Self-Love Dinner", base: "A classic romantic scene of a single person at a candlelit dinner for one." },
                { id: "Love Letter", base: "A thoughtful photo of a single person writing or reading a heartfelt love letter." },
                { id: "Romantic Stroll", base: "A romantic walk of a single person through a beautiful park or city street." },
                { id: "Heart Balloons", base: "A playful and fun photo of a single person holding a large bouquet of heart-shaped balloons." },
            ],
            Diwali: [
                { id: "Diya Glow", base: "A beautiful close-up portrait of a single person illuminated by the warm glow of a traditional diya." },
                { id: "Rangoli Creation", base: "A colorful photo of a single person creating a vibrant rangoli pattern on the floor." },
                { id: "Sparkler Night", base: "A magical photo of a single person at night, surrounded by the light of sparklers." },
                { id: "Festive Attire", base: "A stunning portrait of a single person in bright, traditional Indian festive wear." },
                { id: "Sweet Indulgence", base: "A happy shot of a single person enjoying a variety of colorful Diwali sweets." },
                { id: "Celebratory Portrait", base: "A warm and joyful photo of a single person celebrating amidst lights and decorations." },
            ],
            Halloween: [
                { id: "Pumpkin Patch Fun", base: "A classic, fun photo of a single person sitting among pumpkins in a pumpkin patch." },
                { id: "Spooky Graveyard", base: "A spooky (but safe) photo of a single person in a foggy, atmospheric graveyard setting." },
                { id: "Witch's Cauldron", base: "A magical photo of a single person as a witch, stirring a glowing, bubbling cauldron." },
                { id: "Vampire's Bite", base: "A dramatic, gothic-style portrait of a single person as a vampire." },
                { id: "Friendly Ghost", base: "A cute and playful photo of a single person under a white sheet, peeking out as a friendly ghost." },
                { id: "Trick-or-Treating", base: "A colorful photo of a single person on a decorated porch, ready to go trick-or-treating." },
            ],
            Holi: [
                { id: "Colorful Portrait", base: "A joyful portrait of a single person with colorful powder on their face and clothes, smiling brightly." },
                { id: "Powder Toss", base: "An energetic action shot of a single person throwing colored powder into the air." },
                { id: "Water Splash", base: "A happy photo of a single person being splashed with colored water." },
                { id: "Face Close-up", base: "A close-up of a single person's face, beautifully decorated with vibrant Holi colors." },
                { id: "Joyful Dance", base: "A single person dancing joyfully amidst a celebration of Holi." },
                { id: "Holding Sweets", base: "A portrait of a single person holding a plate of traditional Holi sweets." },
            ],
            "Independence Day": [
                { id: "Flag Bearer", base: "A patriotic portrait of a single person holding a national flag against a sunset sky." },
                { id: "Watching Fireworks", base: "A photo of a single person watching a spectacular fireworks display." },
                { id: "Festive Barbecue", base: "A fun shot of a single person enjoying a barbecue or picnic with festive decorations." },
                { id: "Parade Celebration", base: "A single person dressed in red, white, and blue, celebrating at a parade." },
                { id: "Sparkler Joy", base: "A portrait of a single person with sparklers, creating light trails in the dark." },
                { id: "Outdoor Concert", base: "A single person sitting on a picnic blanket, watching an outdoor concert." },
            ],
            Thanksgiving: [
                { id: "Carving the Turkey", base: "A warm portrait of a single person carving a roast turkey at the head of a festive table." },
                { id: "Pumpkin Pie", base: "A cozy photo of a single person holding a slice of pumpkin pie by a fireplace." },
                { id: "Setting the Table", base: "A single person setting a beautiful Thanksgiving dinner table." },
                { id: "Gratitude Moment", base: "A portrait of a single person writing down what they are thankful for." },
                { id: "Autumn Walk", base: "A single person enjoying a crisp autumn walk after a Thanksgiving meal." },
                { id: "Warm Drink", base: "A close-up of a single person's hands holding a warm mug, with a festive table in the background." },
            ],
            "Boxing Day": [
                { id: "Relaxing with Gifts", base: "A cozy photo of a single person relaxing on a sofa, surrounded by opened Christmas gifts." },
                { id: "Winter Walk", base: "A single person enjoying a walk in a crisp winter landscape." },
                { id: "Watching Sports", base: "A portrait of a single person watching a sports match on TV." },
                { id: "Enjoying Leftovers", base: "A photo of a single person enjoying leftovers from a holiday feast." },
                { id: "Shopping Fun", base: "A single person shopping during the Boxing Day sales." },
                { id: "Spirit of Giving", base: "A portrait of a single person donating to a charity box, embodying the spirit of giving." },
            ],
            "St Patricks Day": [
                { id: "Festive Portrait", base: "A festive portrait of a single person wearing a green top hat and a shamrock pin." },
                { id: "Cheerful Pub", base: "A fun photo of a single person in a cheerful pub decorated for St. Patrick's Day." },
                { id: "Parade Joy", base: "A joyful shot of a single person with a painted shamrock on their cheek at a parade." },
                { id: "Clover Field", base: "A single person searching for a four-leaf clover in a green field." },
                { id: "Pot of Gold", base: "A portrait of a single person holding a pot of 'gold' at the end of a rainbow." },
                { id: "Green Treat", base: "A single person enjoying a green-themed treat or drink." },
            ],
            Hanami: [
                { id: "Blossom Picnic", base: "A serene portrait of a single person having a picnic under blooming cherry blossom trees." },
                { id: "Touching Blossoms", base: "A beautiful photo of a single person gently touching a branch of cherry blossoms." },
                { id: "Petal Path", base: "A single person walking down a path lined with cherry blossom trees, with petals falling." },
                { id: "Petal on Face", base: "A close-up of a single person with a cherry blossom petal on their face." },
                { id: "Eating Dango", base: "A photo of a single person enjoying dango (sweet dumplings) under the blossoms." },
                { id: "Night Sakura", base: "A night portrait of a single person under illuminated cherry trees (Yozakura)." },
            ],
            Oktoberfest: [
                { id: "Bavarian Attire", base: "A cheerful portrait of a single person in traditional Bavarian attire (Lederhosen or Dirndl)." },
                { id: "Raising a Stein", base: "A photo of a single person raising a large beer stein in a festive beer tent." },
                { id: "Giant Pretzel", base: "A fun shot of a single person enjoying a giant pretzel." },
                { id: "Carnival Ride", base: "A single person on a carnival ride with colorful lights in the background." },
                { id: "Listening to Music", base: "A portrait of a single person listening to a traditional Bavarian band." },
                { id: "Cheers!", base: "A joyful photo of a single person toasting to the camera." },
            ],
            Carnival: [
                { id: "Elaborate Mask", base: "A vibrant portrait of a single person wearing an elaborate mask and colorful beads." },
                { id: "Parade Float", base: "An energetic photo of a single person dancing on a float during a parade." },
                { id: "Catching Beads", base: "A joyful shot of a single person catching beads." },
                { id: "Festive Makeup", base: "A close-up of a single person's face painted with festive colors and glitter." },
                { id: "King Cake", base: "A photo of a single person enjoying a slice of King Cake." },
                { id: "Full Costume", base: "A portrait of a single person in a full, spectacular costume against a backdrop of street celebrations." },
            ],
            "Mardi Gras": [
                { id: "Purple, Green, Gold", base: "A festive portrait of a single person wearing purple, green, and gold attire and beads." },
                { id: "Balcony View", base: "A photo of a single person on a French Quarter balcony, ready to toss beads." },
                { id: "Street Performer", base: "An energetic shot of a single person dancing with a street performer." },
                { id: "Masked Ball", base: "An elegant photo of a single person in a mysterious mask at a masquerade ball." },
                { id: "Enjoying Beignets", base: "A delicious shot of a single person enjoying powdered sugar beignets." },
                { id: "Parade Vibe", base: "A portrait of a single person amidst the excitement and color of a Mardi Gras parade." },
            ],
            Obon: [
                { id: "Floating Lantern", base: "A serene photo of a single person lighting a paper lantern to float on a river at dusk." },
                { id: "Yukata Portrait", base: "A respectful portrait of a single person in a yukata, visiting a family grave." },
                { id: "Bon Odori Dance", base: "A photo of a single person watching or participating in a Bon Odori dance." },
                { id: "Home Altar", base: "A quiet, reflective moment of a single person in front of a home altar with offerings." },
                { id: "Watching Taiko", base: "A portrait of a single person watching taiko drummers perform at a festival." },
                { id: "Hanging Chochin", base: "A single person hanging a chochin (paper lantern) outside their home." },
            ],
            "Day of the Dead": [
                { id: "Sugar Skull Makeup", base: "A beautiful portrait of a single person with intricate sugar skull (Calavera) face paint." },
                { id: "Ofrenda Offering", base: "A respectful photo of a single person placing marigolds on an ofrenda (altar)." },
                { id: "Candlelit Vigil", base: "A single person in elegant attire, holding a candle in a cemetery filled with decorations." },
                { id: "Holding a Skull", base: "A close-up of a single person holding a decorated sugar skull." },
                { id: "Papel Picado", base: "A portrait of a single person surrounded by vibrant papel picado banners." },
                { id: "Pan de Muerto", base: "A single person enjoying Pan de Muerto next to a colorful ofrenda." },
            ],
            Songkran: [
                { id: "Water Splash Fun", base: "A joyful, action shot of a single person getting splashed with water during the festival." },
                { id: "Water Pistol", base: "A happy photo of a single person using a water pistol, smiling brightly." },
                { id: "Buddha Statue", base: "A respectful photo of a single person gently pouring scented water over a Buddha statue." },
                { id: "Floral Shirt", base: "A portrait of a single person wearing a colorful floral shirt." },
                { id: "White Clay", base: "A candid photo of a single person applying din sor pong (white clay) on their own face." },
                { id: "Morning Offering", base: "A single person offering food to monks in the morning." },
            ]
        }
    },
    costumes: {
        name: 'Costumes',
        imageUrl: 'https://placehold.co/600x900/a855f7/ffffff?text=Costumes',
        description: 'Dress up as your favorite characters.',
        isPolaroid: false,
        prompts: [
            { id: "Elegant Witch", base: "Stylish witch with flowing black outfit, pointed hat, moonlit forest backdrop, soft mist, glowing staff, cinematic fantasy lighting, fashion editorial tone." },
            { id: "Gothic Vampire", base: "Charming vampire in vintage suit, candlelit mansion, gothic window light, red velvet tones, elegant and mysterious expression, cinematic chiaroscuro." },
            { id: "Ethereal Angel", base: "Heavenly being surrounded by soft clouds and glowing aura, flowing white fabric, radiant golden light, serene atmosphere, ethereal beauty aesthetic." },
            { id: "Adventurous Pirate", base: "Cinematic pirate on wooden ship deck, sunset over ocean, worn leather jacket, adventurous pose, dramatic orange lighting and sea breeze." },
            { id: "Forest Fairy", base: "Whimsical fairy surrounded by glowing flora, pastel wings, magical sparkles in the air, dreamlike soft-focus lighting, fantasy realism." },
            { id: "Western Cowboy", base: "Stylish cowboy in denim and leather, golden sunset over dusty plains, cinematic lens flare, confident pose, rustic textures." },
        ]
    },
    decades: {
        name: 'Time Traveler',
        imageUrl: 'https://placehold.co/600x800/7c3aed/ffffff?text=Time+Traveler',
        description: 'See yourself through the decades.',
        isPolaroid: true,
        prompts: [
            { id: '1950s', base: 'A 1950s style portrait.' },
            { id: '1960s', base: 'A 1960s style portrait.' },
            { id: '1970s', base: 'A 1970s style portrait.' },
            { id: '1980s', base: 'An 1980s style portrait.' },
            { id: '1990s', base: 'A 1990s style portrait.' },
            { id: '2000s', base: 'A 2000s style portrait.' },
        ]
    },
    socialMedia: {
        name: "Social Media",
        imageUrl: 'https://placehold.co/600x600/db2777/ffffff?text=Social+Media',
        description: "Profile pictures for every platform.",
        isPolaroid: false,
        // Prompts are derived from selected platform
        platforms: {
            Professional: [
                { id: 'LinkedIn', base: 'a polished, professional studio headshot with a neutral background.' },
                { id: 'GitHub', base: 'a tech-focused developer portrait, clean and modern.' },
                { id: 'Slack', base: 'an approachable and friendly corporate headshot.' },
                { id: 'Teams', base: 'a clear and professional headshot for a work chat app.' },
            ],
            Creator: [
                { id: 'Instagram', base: 'a stylish, editorial-style photo with a creative flair.' },
                { id: 'TikTok', base: 'an energetic, expressive selfie with vibrant lighting.' },
                { id: 'YouTube', base: 'an expressive, high-energy thumbnail-style portrait.' },
                { id: 'Twitch', base: 'a cool gamer portrait with neon lighting.' },
                { id: 'Discord', base: 'a stylized gamer aesthetic profile picture.' },
                { id: 'Pinterest', base: 'a dreamy, gentle, and aesthetically pleasing photo.' },
            ],
            Social: [
                { id: 'Facebook', base: 'a friendly, casual lifestyle photo.' },
                { id: 'X (Twitter)', base: 'a minimal, witty, and modern-style headshot.' },
                { id: 'Threads', base: 'a candid and engaging photo with a clean aesthetic.' },
                { id: 'Snapchat', base: 'a spontaneous, fun, and playful selfie.' },
                { id: 'Reddit', base: 'an authentic, informal, and community-focused picture.' },
                { id: 'Bluesky', base: 'an understated, community-forward, and relaxed photo.' },
                { id: 'Mastodon', base: 'an authentic and independent-spirited profile picture.' },
            ],
            Dating: [
                { id: 'Tinder', base: 'a confident and attractive headshot that stands out.' },
                { id: 'Hinge', base: 'an authentic and warm photo that shows off your personality.' },
                { id: 'Bumble', base: 'a bright, friendly, and empowering profile picture.' },
                { id: 'Badoo', base: 'a casual, fun, and approachable photo.' },
            ],
            Exclusive: [
                { id: 'OnlyFans', base: 'a tasteful and alluring glamour portrait.' },
            ],
            Messaging: [
                { id: 'WhatsApp', base: 'a natural and crisp headshot for personal communication.' },
                { id: 'Telegram', base: 'a clear and modern profile picture.' },
                { id: 'Signal', base: 'a simple, high-quality, and private-feeling headshot.' },
            ]
        }
    },
    stickers: {
        name: "Sticker Pack",
        imageUrl: 'https://placehold.co/600x700/ea580c/ffffff?text=Stickers',
        description: "Create custom die-cut stickers.",
        isPolaroid: false,
        prompts: [
            { id: 'Pop Art', base: 'A vibrant pop art sticker with bold colors, thick black lines, and comic book-style dots.' },
            { id: 'Cartoon Dino', base: 'A cool cartoon dinosaur sticker with a playful, edgy attitude and sharp outlines.' },
            { id: 'Pixel Art', base: 'A retro 8-bit pixel art sticker with a limited color palette.' },
            { id: 'Claymation', base: 'A charming claymation-style sticker with visible fingerprints and soft, rounded textures.' },
            { id: 'Vintage Toon', base: 'A rubber hose, 1930s-style vintage cartoon sticker in black and white.' },
            { id: 'Holographic', base: 'A shiny, holographic sticker that seems to shift colors with the light.' },
        ]
    },
    styleLookbook: {
        name: "Style Lookbook",
        imageUrl: 'https://placehold.co/600x900/0891b2/ffffff?text=Style+Lookbook',
        description: "Your personal fashion photoshoot.",
        isPolaroid: false,
        styles: [
            'Classic / Casual', 'Streetwear', 'Vintage', 'Goth', 'Preppy', 'Minimalist',
            'Athleisure', 'Old Money / Quiet Luxury', 'Bohemian (Boho)', 'Business Casual',
            '90s Grunge', 'Cocktail / Formal'
        ],
        prompts: [
            { id: 'Look 1', base: 'a full-body shot, standing' },
            { id: 'Look 2', base: 'a half-body shot, smiling' },
            { id: 'Look 3', base: 'a candid walking shot' },
            { id: 'Look 4', base: 'a shot showing off outfit details' },
            { id: 'Look 5', base: 'a seated pose' },
            { id: 'Look 6', base: 'a close-up shot focusing on accessories' },
        ]
    },
    eightiesMall: {
        name: "'80s Mall Shoot",
        imageUrl: "https://placehold.co/600x750/be185d/ffffff?text='80s+Mall",
        description: "Totally tubular 1980s portraits.",
        isPolaroid: false,
        prompts: [
            { id: 'Smiling', base: 'a friendly, smiling pose' },
            { id: 'Thoughtful', base: 'a thoughtful, looking away from the camera pose' },
            { id: 'Fun', base: 'a fun, laughing pose' },
            { id: 'Serious', base: 'a serious, dramatic pose' },
            { id: 'Hand on Chin', base: 'posing with their hand on their chin' },
            { id: 'Over the Shoulder', base: 'looking back over their shoulder' },
        ]
    },
    figurines: {
        name: 'Miniature Me',
        imageUrl: 'https://placehold.co/600x600/ca8a04/ffffff?text=Miniature+Me',
        description: 'Your own collectible figurines.',
        isPolaroid: false,
        prompts: [
            { id: 'Bobblehead', base: 'A realistic bobblehead figure of the person with an oversized head, displayed on a polished wooden desk next to a computer keyboard.' },
            { id: 'Porcelain Figurine', base: 'A delicate souvenir porcelain figurine of the person, painted with glossy colors, sitting on a lace doily on a vintage dresser.' },
            { id: 'Retro Action Figure', base: 'A retro 1980s-style action figure of the person, complete with articulated joints and slightly worn paint, posed in a dynamic stance on a rocky diorama base.' },
            { id: 'Vinyl Figure', base: 'A stylized collectible vinyl art toy of the person with minimalist features, standing on a shelf filled with other similar toys.' },
            { id: 'Plushy Figure', base: 'A soft, cute plushy figure of the person with detailed fabric texture and stitching, sitting on a neatly made bed.' },
            { id: 'Wooden Folk Art', base: 'A hand-carved wooden folk art figure of the person, painted with rustic, charming details, standing on a simple wooden block on a craft fair table.' },
        ]
    },
    hairStyler: {
        name: 'Hair Styler',
        imageUrl: 'https://placehold.co/600x800/65a30d/ffffff?text=Hair+Styler',
        description: 'Try on new hairstyles and colors.',
        isPolaroid: false,
        hairColors: ['Blonde', 'Brown', 'Black', 'Red', 'Silver', 'Pastel Pink', 'Blue', 'Purple', 'Green', 'Ombre'],
        prompts: [
            { id: 'Short', base: 'a short hairstyle' },
            { id: 'Medium', base: 'a medium-length hairstyle' },
            { id: 'Long', base: 'a long hairstyle' },
            { id: 'Straight', base: 'straight hair' },
            { id: 'Wavy', base: 'wavy hair' },
            { id: 'Curly', base: 'curly hair' },
        ]
    },
    impossibleSelfies: {
        name: 'Impossible Pics',
        imageUrl: 'https://placehold.co/600x700/1d4ed8/ffffff?text=Impossible+Pics',
        description: 'Photos that defy reality.',
        isPolaroid: false,
        prompts: [
            { id: 'With Lincoln', base: 'The person posing with Abraham Lincoln, who is also making a peace sign and sticking his tongue out. Keep the original location.' },
            { id: 'Alien & Bubbles', base: 'The person posing next to a realistic alien holding two bubble guns, blowing thousands of bubbles. Keep the person\'s pose and the original location.' },
            { id: 'Room of Puppies', base: 'The person posing in a room filled with a hundred different puppies.' },
            { id: 'Singing Puppets', base: 'The person posing in a room full of large, whimsical, brightly colored felt puppets that are singing.' },
            { id: 'Giant Chicken Tender', base: 'The person posing with their arm around a 4-foot-tall chicken tender. Keep the person\'s facial expression exactly the same.' },
            { id: 'Yeti Photobomb', base: 'Add a realistic yeti standing next to the person on the left side of the photo, matching the lighting. Keep the person\'s pose and face exactly the same.' },
        ]
    },
    headshots: {
        name: "Pro Headshots",
        imageUrl: 'https://placehold.co/600x900/4b5563/ffffff?text=Pro+Headshots',
        description: "Professional profile pictures.",
        isPolaroid: false,
        expressions: ['Friendly Smile', 'Serious', 'Approachable', 'Confident', 'Neutral', 'Laughing'],
        poses: ['Forward', 'Side Profile', 'Three-Quarter', 'Arms Crossed', 'Hands in Pockets'],
        prompts: [
            { id: 'Business Suit', base: 'wearing a dark business suit with a crisp white shirt' },
            { id: 'Smart Casual', base: 'wearing a smart-casual knit sweater over a collared shirt' },
            { id: 'Creative Pro', base: 'wearing a dark turtleneck' },
            { id: 'Corporate Look', base: 'wearing a light blue button-down shirt' },
            { id: 'Bright & Modern', base: 'wearing a colorful blazer' },
            { id: 'Relaxed', base: 'wearing a simple, high-quality t-shirt under a casual jacket' },
        ]
    },
};
